name: js
authors: ["Dart Team <misc@dartlang.org>", "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"]
homepage: https://github.com/dart-lang/js-interop
description: Access JavaScript from Dart.
version: 0.0.14
dependencies:
  browser: ">=0.0.1 <0.0.2"
  unittest: any
