name: js
version: 0.0.25
authors:
- Dart Team <misc@dartlang.org>
- Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Access JavaScript from Dart.
homepage: https://github.com/dart-lang/js-interop
dependencies:
  browser: any
  meta: any
dev_dependencies:
  ghpages_generator: any
  path: any
  unittest: any
